name: mask-input

inputs:
  input-name:
    type: string
    required: true
  output-variable-name:
    type: string
    required: true

  runs:
    using: composite
    steps:
      shell: bash
      run: |
        # see https://dev.to/leading-edje/masking-input-parameters-in-github-actions-1ci
        ${{ inputs.output-variable-name }}=$(jq -r '.inputs."${{ inputs.input-name }}"' $GITHUB_EVENT_PATH)
        echo ::add-mask::$${{ inputs.output-variable-name }}
        echo ${{ inputs.output-variable-name }}=$${{ inputs.output-variable-name }} >> $GITHUB_ENV
