name: assemble-release

inputs:
  artifacts:
    type: string
  output-file-name:
    type: string

runs:
  using: composite
  steps:
    - name: Assemble Release
      shell: bash
      run: |
        mkdir ${{ env.RELEASE_STAGING }}
        # TODO: delete pdb files?  run some kind of assembly script?
        cp -r -v ${{ inputs.artifacts }} ${{ env.RELEASE_STAGING }} || :

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-file-name }}
        path: ${{ env.RELEASE_STAGING }}
        if-no-files-found: error
