name: assemble-release

inputs:
  artifacts:
    type: string
    default: GameData LICENSE* README* CHANGELOG*
  output-file-name:
    type: string
    default: ${{ github.event.repository.name }}

outputs:
  artifact-id:
    value: ${{ steps.upload-artifact.outputs.artifact-id }}
  artifact-url:
    value: ${{ steps.upload-artifact.outputs.artifact-url }}

runs:
  using: composite
  steps:
    - name: Assemble Release
      shell: bash
      run: |
        mkdir ${{ env.RELEASE_STAGING }}
        # TODO: delete pdb files?  run some kind of assembly script?
        cp -r -v ${{ inputs.artifacts }} ${{ env.RELEASE_STAGING }} || :

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.output-file-name }}
        path: ${{ env.RELEASE_STAGING }}
        if-no-files-found: error
