name: compile

inputs:
  build-configuration:
    type: string
    default: Release
  ksp-zip-url:
    type: string
    default: https://github.com/KSPModdingLibs/KSPLibs/raw/main/KSP-1.12.5.zip
  ksp-zip-password:
    type: string
  dependency-identifiers:
    type: string

runs:
  using: composite
  steps:

    - name: dump contexts
      shell: bash
      if: env.ACTIONS_STEP_DEBUG
      run: |
        echo "${{ toJson(env) }}"
        echo "${{ toJson(github )}}"
        echo "${{ toJson(job) }}"
        echo "${{ toJson(steps) }}"
        printenv

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.x

    - name: Install Dependencies
      if: inputs.dependency-identifiers != ''
      uses: KSPModdingLibs/KSPBuildTools/.github/actions/install-dependencies@main
      with:
        dependency-identifiers: ${{ inputs.dependency-identifiers }}

    - name: Download KSP Libs
      shell: bash
      run: |
        wget --quiet ${{ inputs.ksp-zip-url }} -O /tmp/ksp.zip
        unzip -q -P "${{ inputs.ksp-zip-password }}" /tmp/ksp.zip -d "${{ env.KSP_ROOT }}"

    - name: Restore NuGet Packages
      shell: bash
      working-directory: ${{ github.workspace }}
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build Mod Solution
      shell: bash
      working-directory: ${{ github.workspace }}
      run: msbuild /p:Configuration=${{ inputs.build-configuration }} /p:KSPRoot=${{ env.KSP_ROOT }} /p:ManagedRelativePath=KSP_x64_Data/Managed ${{ env.SOLUTION_FILE_PATH }}

