name: Setup Unity
description: Installs the Unity Editor

inputs:
  editor-version:
    description: >
      CKAN tag to install. set to an empty string to always install the most recent version. 
      See https://github.com/KSP-CKAN/CKAN/tags for a list of available tags
    default: ''

runs:
  using: composite
  steps:
    - name: Install Unity public key
      shell: bash
      run: >-
        wget -qO - https://hub.unity3d.com/linux/keys/public 
        | gpg --dearmor 
        | sudo tee /usr/share/keyrings/Unity_Technologies_ApS.gpg > /dev/null

    - name: Install Unity apt package
      shell: bash
      run: |
        sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/Unity_Technologies_ApS.gpg] https://hub.unity3d.com/linux/repos/deb stable main" > /etc/apt/sources.list.d/unityhub.list'
        sudo apt update

    - name: Install Unity hub
      uses: tecolicom/actions-use-apt-tools@v1
      with:
        tools: 'unityhub'