name: update-version

inputs:
  version-string:
    type: string
  template-extension:
    type: string
    default: .versiontemplate
  files:
    type: string
  ksp-build-tools-root:
    type: string
    default: tmp/kspbuildtools #note this is relative to the *mod*'s repository
  changelog-input-file:
    type: string
    default: CHANGELOG.md
  changelog-output-file:
    type: string

runs:
  using: composite
  steps:
    - name: checkout kspbuildtools
      uses: actions/checkout@v4
      with:
        repository: KSPModdingLibs/KSPBuildTools
        path: ${{inputs.ksp-build-tools-root}}
        sparse-checkout: update-version.sh
        sparse-checkout-cone-mode: false

    - name: update-changelog
      working-directory: ${{ github.workspace }}
      if: ${{ hashFiles( inputs.changelog-input-file ) != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install yaclog yaclog-ksp
        yaclog release --path ${{ inputs.changelog-input-file }} -f ${{ inputs.version-string }}
        yaclog-ksp -n ${{ github.event.repository.name }} -o ${{ inputs.changelog-output-file }};
        git add ${{ inputs.changelog-output-file }}

    - name: update version
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        SCRIPT="${{inputs.ksp-build-tools-root}}/update-version.sh"
        chmod +x $SCRIPT
        $SCRIPT -g true -d true ${{inputs.version-string}} ${{inputs.template-extension}} ${{inputs.files}}

