name: update-version

inputs:
  version-string:
    type: string
  template-extension:
    type: string
    default: .versiontemplate
  files:
    type: string

runs:
  using: composite
  env:
    KSPBUILDTOOLS_ROOT: /tmp/kspbuildtools
  steps:
    - name: checkout kspbuildtools
      uses: actions/checkout@v4
      with:
        repository: KSPModdingLibs/KSPBuildTools
        path: ${{env.KSPBUILDTOOLS_ROOT}}
        sparse-checkout: update-version.sh
        sparse-checkout-cone-mode: false

    - name: update version
      shell: bash
      run: |
        if [-n "${{inputs.files}}" ]; then
          FILES="**/*${{inputs.template-extension}}"
        else
          FILES=${{inputs.files}}
        fi
        ${{env.KSPBUILDTOOLS_ROOT}}/update-version.sh ${{inputs.version-string}} $FILES

