name: update-version

inputs:
  version-string:
    type: string
  template-extension:
    type: string
    default: .versiontemplate
  files:
    type: string
  ksp-build-tools-root:
    type: string
    default: /tmp/kspbuildtools

runs:
  using: composite
  steps:
    - name: checkout kspbuildtools
      uses: actions/checkout@v4
      with:
        repository: KSPModdingLibs/KSPBuildTools
        path: ${{inputs.ksp-build-tools-root}}
        sparse-checkout: update-version.sh
        sparse-checkout-cone-mode: false

    - name: update version
      shell: bash
      run: |
        if [-n "${{inputs.files}}" ]; then
          FILES="**/*${{inputs.template-extension}}"
        else
          FILES=${{inputs.files}}
        fi
        ${{inputs.ksp-build-tools-root}}/update-version.sh ${{inputs.version-string}} $FILES

