name: update-version

inputs:
  version-string:
    type: string
  template-extension:
    type: string
    default: .versiontemplate
  files:
    type: string
  ksp-build-tools-root:
    type: string
    default: tmp/kspbuildtools #note this is relative to the *mod*'s repository
  git-stage:
    type: boolean
    default: false
  delete-template-files:
    type: boolean
    default: false
  changelog-input-file:
    type: string
    default: CHANGELOG.md
  changelog-output-file:
    type: string

runs:
  using: composite
  steps:
    - name: checkout kspbuildtools
      uses: actions/checkout@v4
      with:
        repository: KSPModdingLibs/KSPBuildTools
        path: ${{inputs.ksp-build-tools-root}}
        sparse-checkout: update-version.sh
        sparse-checkout-cone-mode: false

    - name: update-changelog
      working-directory: ${{ github.workspace }}
      if: ${{ hashFiles(inputs.changelog-input-file) != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install yaclog yaclog-ksp
        yaclog release --path ${{ inputs.changelog-input-file }} -f ${{ inputs.version-string }}
        yaclog-ksp -n ${{ github.event.repository.name }} -o ${{ changelog-output-file }};
        if ${{git-stage}}; then
          git add ${{ changelog-output-file }}
        fi

    - name: update version
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        SCRIPT="${{inputs.ksp-build-tools-root}}/update-version.sh"
        chmod +x $SCRIPT
        $SCRIPT -g ${{ inputs.git-stage }} -d ${{ inputs.delete-template-files }} ${{inputs.version-string}} ${{inputs.template-extension}} ${{inputs.files}}

