name: update-version

inputs:
  version-string:
    type: string
  template-extension:
    type: string
    default: .versiontemplate
  files:
    type: string
  ksp-build-tools-root:
    type: string
    default: tmp/kspbuildtools #note this is relative to the *mod*'s repository

runs:
  using: composite
  steps:
    - name: checkout kspbuildtools
      uses: actions/checkout@v4
      with:
        repository: KSPModdingLibs/KSPBuildTools
        path: ${{inputs.ksp-build-tools-root}}
        sparse-checkout: update-version.sh
        sparse-checkout-cone-mode: false

    - name: update version
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        if [ -n "${{inputs.files}}" ]; then
          FILES="**/*${{inputs.template-extension}}"
        else
          FILES=${{inputs.files}}
        fi
        SCRIPT="${{inputs.ksp-build-tools-root}}/update-version.sh"
        chmod +x $SCRIPT
        $SCRIPT ${{inputs.version-string}} $FILES

