name: Build Assetbundle
description: Build an assetbundle

inputs: 
  unity-version:
    description: Full unity version name to build with. e.g. 2019.4.18f1
    default: '2019.4.18f1'

  project-dir:
    description: Location of the Unity project root (The folder that contains `Assets`) *relative to the github workspace*
    default: .

  assetbundle-dir:
    description: Destination for built assetbundles

  unity-password:
    description: Your Unity account password

  unity-username:
    description: Your Unity account username

  unity-license:
    description: Your Unity ULF file contents

runs:
  using: composite
  steps:
    - name: Copy editor tools into project
      shell: bash
      run: |
        mkdir -p ${{ inputs.project-dir }}/Assets/KSPBuildTools
        cp -r ${{ github.action_path }}/../../../Editor ${{ inputs.project-dir }}/Assets/KSPBuildTools/Editor

    - uses: game-ci/unity-builder@v4
      with:
        targetPlatform: 'StandaloneWindows'
        unityVersion: ${{ inputs.unity-version }}
        projectPath: ${{ project-dir }}
        customParameters: '-assetbundlePath /github/workspace/${{ inputs.assetbundle-dir }}'
        buildMethod: 'AssetBundleBuilder.BuildBundles'

