name: Build Assetbundle
description: Build an assetbundle

inputs:
  unity-version:
    description: Full unity version name to build with. e.g. 2019.4.18f1
    default: '2019.4.18f1'

  project-dir:
    description: Location of the Unity project root (The folder that contains `Assets`) *relative to the github workspace*
    default: .

  assetbundle-dir:
    description: Destination for built assetbundles
    default: 'Bundle'

runs:
  using: composite
  steps:
    - name: Calculate destination directory
      shell: bash
      run: |
        echo "ASSETBUNDLE_TMP=AssetBundles/${{ hashFiles(format('{0}/**', inputs.project-dir)) }}" >> $GITHUB_ENV

    - name: Make destination directory
      shell: bash
      run: |
        mkdir -p ${{ env.ASSETBUNDLE_TMP }}
        mkdir -p ${{ inputs.assetbundle-dir }}

    - uses: actions/cache@v4
      with:
        path: ${{ inputs.project-dir }}/Library
        key: library-${{ env.ASSETBUNDLE_TMP }}
        restore-keys: |
          library-${{ env.ASSETBUNDLE_TMP }}
          library-

    - name: Copy editor tools into project
      shell: bash
      run: |
        mkdir -p ${{ inputs.project-dir }}/Assets/KSPBuildTools/Editor
        cp ${{ github.action_path }}/AssetBundleBuilder.cs ${{ inputs.project-dir }}/Assets/KSPBuildTools/Editor/

    - uses: game-ci/unity-builder@v4
      with:
        targetPlatform: 'StandaloneWindows64'
        unityVersion: ${{ inputs.unity-version }}
        projectPath: ${{ inputs.project-dir }}
        customParameters: '-assetbundlePath /github/workspace/${{ env.ASSETBUNDLE_TMP }}'
        buildMethod: 'KSPBuildTools.AssetBundleBuilder.BuildBundles'
        allowDirtyBuild: true
        versioning: None

    - name: Copy bundles to target directory
      shell: bash
      run: |
        cp ${{ env.ASSETBUNDLE_TMP }}/*  ${{ inputs.assetbundle-dir }}/
      env:
        GLOBIGNORE: '*.manifest'
