name: Build Assetbundle
description: Build an assetbundle

inputs: 
  unity-version:
    description: Full unity version name to build with. e.g. 2019.4.18f1
    default: '2019.4.18f1'

  project-dir:
    description: Location of the Unity project root (The folder that contains `Assets`) *relative to the github workspace*
    default: .

  assetbundle-dir:
    description: Destination for built assetbundles

runs:
  using: composite
  steps:
    - name: Build Docker Container
      shell: bash
      run: |
        docker build --platform linux/amd64 --tag build-assetbundle --file ${{ github.action_path }}/Dockerfile --build-arg UNITY_VERSION=${{inputs.unity-version}} .
      working-directory: ${{ github.action_path }}/../../..
      
    - name: Start Docker Container
      shell: bash
      run: >
        docker run --name build-assetbundle 
        -d -i -t 
        --volume ${{ github.workspace }}:/github/workspace 
        build-assetbundle 

    - name: Copy editor tools into project
      shell: bash
      run: |
        mkdir -p ${{ inputs.project-dir }}/Assets/KSPBuildTools
        cp -r ${{ github.action_path }}/../../../Editor ${{ inputs.project-dir }}/Assets/KSPBuildTools/Editor

    - name: Run assetbundle build
      shell: bash
      run: >
        docker exec -d build-assetbundle 
        unity-editor 
          -batchmode 
          -nographics 
          -projectPath /github/workspace/${{ inputs.project-dir }} 
          -executeMethod AssetBundleBuilder.BuildBundles
          -assetbundlePath /github/workspace/${{ inputs.assetbundle-dir }}
          -quit
        
    - name: Shutdown Docker Container
      shell: bash
      run: docker stop build-assetbundle


