name: build

on:
  workflow_call:
    inputs:
      build-configuration:
        type: string
        default: Release
      artifacts:
        type: string
        default: GameData LICENSE* README* CHANGELOG*
      ksp-zip-url:
        type: string
        default: https://github.com/KSPModdingLibs/KSPBuildTools/raw/main/KSP-1.12.5.zip
      version-string:
        type: string
    secrets:
      ksp-zip-password:
        required: false

env:
  KSP_ROOT: /tmp/ksp
  RELEASE_STAGING: /tmp/release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          # working around a bug in checkout action: https://github.com/actions/checkout/issues/1418#issuecomment-1899122964
          ref: "${{ github.head_ref || github.ref }}"

      - name: update-version
        if: ${{ inputs.version-string != '' }}
        uses: ./.github/actions/update-version
        with:
          version-string: ${{ inputs.version-string }}

      - name: compile
        uses: ./.github/actions/compile
        with:
          build-configuration: ${{ inputs.build-configuration }}
          ksp-zip-url: ${{ inputs.ksp-zip-url }}
          ksp-zip-password: ${{ secrets.ksp-zip-password }}

      - name: assemble-release
        uses: ./.github/actions/assemble-release
        with:
          artifacts: ${{ inputs.artifacts }}
          output-file-name: ${{ github.event.repository.name }}-${{ inputs.version-string || github.ref }}-${{ inputs.build-configuration }}