name: build

on:
  workflow_call:
    inputs:
      build-configuration:
        type: string
        default: Release
      artifacts:
        type: string
        default: GameData LICENSE* README* CHANGELOG*
      ksp-zip-url:
        type: string
      dependency-identifiers:
        type: string
    secrets:
      ksp-zip-password:
        required: false

env:
  KSP_ROOT: /tmp/ksp
  RELEASE_STAGING: /tmp/release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: compile
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/compile@main
        with:
          #build-configuration: ${{ inputs.build-configuration }}
          #ksp-zip-url: ${{ inputs.ksp-zip-url }}
          ksp-zip-password: ${{ secrets.ksp-zip-password }}

      - name: assemble-release
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/assemble-release@main
        with:
          artifacts: ${{ inputs.artifacts }}
          output-file-name: ${{ github.event.repository.name }}-${{ inputs.build-configuration }}
