# playground for ckan

name: ckan

on:
  workflow_dispatch

defaults:
  run:
    shell: bash

env:
  KSP_ROOT: /tmp/ksp

jobs:
  ckan:
    runs-on: ubuntu-latest
    steps:
      - name: install-dependencies
        uses: KSPModdingLibs/KSPBuildTools/install-dependencies@main
        env: ${{ env.KSP_ROOT }}
      
