# This is an internal test for KSPBuildTools and not intended to be used by other projects
name: Test Assetbundle

on:
  workflow_call:

env:
  TESTDIR: tests/plugin-mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: 2019.4.18f1
          unity-modules: windows