# This is an internal test for KSPBuildTools and not intended to be used by other projects
name: Test Assetbundle

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
      UNITY_EMAIL:
      UNITY_PASSWORD:
env:
  TESTDIR: tests/plugin-mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'LGhassen/Deferred'
          path: 'Deferred'

      - run: |
          mkdir -p Deferred/shaders/DeferredKSPShaders/Assets/KSPBuildTools
          cp -r Editor Deferred/shaders/DeferredKSPShaders/Assets/KSPBuildTools/Editor

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: 'StandaloneWindows'
          unityVersion: '2019.4.18f1'
          projectPath: 'Deferred/shaders/DeferredKSPShaders'
          customParameters: '-assetbundlePath /github/workspace/${{ inputs.assetbundle-dir }}'
          buildMethod: 'AssetBundleBuilder.BuildBundles'
          allowDirtyBuild: true
          versioning: None
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

#      - uses: ./.github/actions/build-assetbundles
#        with:
#          project-dir: 'Deferred/shaders/DeferredKSPShaders'
#          assetbundle-dir: 'Bundle'
#          unity-username: ${{ secrets.UNITY_USERNAME }}
#          unity-password: ${{ secrets.UNITY_PASSWORD}}
#          unity-license: ${{ secrets.UNITY_ULF}}
#        env:
#          UNITY_LICENSE: ${{ secrets.UNITY_ULF }}
#          UNITY_EMAIL: ${{ secrets.UNITY_USERNAME}}
#          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}


      - uses: actions/upload-artifact@v4
        with:
          path: 'Bundle'
          name: assetbundle
