# This is an internal test for KSPBuildTools and not intended to be used by other projects
name: Test Assetbundle

on:
  workflow_call:

env:
  TESTDIR: tests/plugin-mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'LGhassen/Deferred'
          path: 'Deferred'

      - uses: ./.github/actions/build-assetbundles
        with:
          project-dir: 'Deferred/shaders/DeferredKSPShaders'
          assetbundle-dir: 'Bundle'
          unity-license: ${{ secrets.UNITY_ULF }}

      - uses: actions/upload-artifact@v4
        with:
          path: 'Bundle'
          name: assetbundle
