name: publish-to-spacedock

on:
  workflow_dispatch:
    inputs:
      spacedock-username:
        type: string
      spacedock-password:
        type: string
      game-id:
        type: number
        default: 3102 # hardcoded to KSP1 gameid.  retrieve from https://spacedock.info/api/games
      mod-id:
        type: number
        required: true

env:
  SPACEDOCK_USERNAME: ${{ inputs.spacedock-username || github.triggering_actor }}
  SPACEDOCK_PASSWORD: ${{ inputs.spacedock-password || secrets.SPACEDOCK_PASSWORD }}
  SPACEDOCK_MOD_ID: ${{ inputs.mod-id || vars.SPACEDOCK_MOD_ID }}

jobs:
  publish-to-spacedock:
    runs-on: ubuntu-latest
    steps:
      - name: setup-inputs
        run: |
          # see https://dev.to/leading-edje/masking-input-parameters-in-github-actions-1ci
          SPACEDOCK_PASSWORD=$(jq -r '.inputs.spacedock-password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$SPACEDOCK_PASSWORD
          echo SPACEDOCK_PASSWORD=$SPACEDOCK_PASSWORD >> $GITHUB_ENV

      - name: get-release-info
        if: false
        run: 
          gh release view

      - name: upload-to-spacedock
        if: false
        uses: KSP2Community/spacedock-upload@v1.0.0
        with:
          username: ${{ env.SPACEDOCK_USERNAME }}
          password: ${{ env.SPACEDOCK_PASSWORD }}
