name: publish-to-spacedock

on:
  workflow_call:
    inputs:
      spacedock-username:
        type: string
        required: true
      mod-id:
        type: string
        required: true
      release-tag:
        type: string
        required: false
      game-id:
        type: string
        required: false
        default: '3102' # hardcoded to KSP1 gameid.  retrieve from https://spacedock.info/api/games
    secrets:
      spacedock-password:
        required: true

jobs:
  publish-to-spacedock:
    runs-on: ubuntu-latest
    steps:
      - name: get-release-info
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/get-release-info@main
        with:
          release-tag: ${{ inputs.release-tag }}

      - name: upload-to-spacedock
        uses: KSP2Community/spacedock-upload@v1.0.0
        with:
          username: ${{ inputs.spacedock-username }}
          password: ${{ secrets.spacedock-password }}
          game_id: ${{ inputs.game-id }}
          mod_id: ${{ inputs.mod-id }}
          version: ${{ steps.get-release-info.outputs.version-string }}
          zipball: ${{ steps.get-release-info.outputs.artifact-file }}
          changelog: ${{ steps.get-release-info.outputs.changelog-file }}
