name: update-version

on:
  workflow_call:
    inputs:
      version-string:
        type: string
      template-extension:
        type: string
        default: .versiontemplate
      files:
        type: string

defaults:
  run:
    shell: bash

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout mod repo
        uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: update version
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/update-version@main
        with:
          version-string: ${{inputs.version-string}}
          template-extension: ${{inputs.template-extension}}
          files: ${{inputs.files}}
