name: update-version

on:
  workflow_call:
    inputs:
      version-string:
        type: string
      template-extension:
        type: string
        default: .versiontemplate
      files:
        type: string
        default: "**/*${{inputs.template-extension}}"

defaults:
  run:
    shell: bash

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout mod repo
        uses: actions/checkout@v4
        with:
          # working around a bug in checkout action: https://github.com/actions/checkout/issues/1418#issuecomment-1899122964
          ref: "${{ github.head_ref || github.ref }}"
    
      - name: update version
        uses: KSPModdingLibs/KSPBuildTools/.github/actions/update-version@main
        with:
          version-string: ${{inputs.version-string}}
          template-extension: ${{inputs.template-extension}}
          files: ${{inputs.files}}
